fix: Restore Node 6 support
The trailing comma on functions, which was required due to eslint breaks Node 6

    SyntaxError: Unexpected token )

    lib/parser/annotations.js:46
    );
    ^

Therefore I have disallowed trailing commas specifically for functions.